# Generated by Django 2.1.5 on 2019-02-08 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('famous_clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='famousclients',
            options={'ordering': ['order'], 'verbose_name_plural': 'Famous clients'},
        ),
    ]
