# Generated by Django 2.1.5 on 2019-02-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famous_clients', '0002_auto_20190208_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='famousclients',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
