# Generated by Django 2.1.5 on 2019-01-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_guitar_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
