# Generated by Django 2.1.5 on 2019-01-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0004_auto_20190129_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
