# Generated by Django 2.1.5 on 2019-01-31 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_guitar_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guitar',
            old_name='url',
            new_name='slug',
        ),
    ]
