# Generated by Django 2.1.5 on 2019-01-31 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0007_auto_20190131_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitar',
            name='slug',
        ),
    ]
